backend:
    name: git-gateway
    branch: master

media_folder: /static/images
public_folder: /images/

collections:
    - name: staff
      label: Staff
      folder: /content/staff
      media_folder: '/static/images/staff'
      public_folder: '/images/staff'
      create: true
      fields:
          - { name: title, label: title, required: true }
          - { name: subtitle, label: subtitle, required: true }
          - { name: description, label: Description, required: true }
          - { name: image, label: img, widget: image, required: true }
          - { name: tags, label: classes, widget: list, required: true }
          - { name: color, label: color, widget: select, options: ["red", "orange", "green", "blue"], required: true }
          - { name: link, label: link, widget: string, required: true }
          - { name: body, label: body, widget: markdown, required: true }
    - name: classes
      label: Classes
      folder: /content/classes
      media_folder: '/static/images/classes'
      public_folder: '/images/classes'
      create: true
      fields:
        - {label: "Title", name: title, widget: string}
        - {label: "Date", name: date, widget: string}
        - {label: "Time", name: time, widget: string}
        - {label: "Description", name: description, widget: markdown}
        - {label: "Price", name: price, widget: string}
        - { label: "Category", name: tags, widget: select, options: ["SAT I", "SAT II", "College Consulting", "AP Prep", "Math/Science", "English", "Individual Tutor"], required: true }
        - {label: "Teacher Name", name: teacherName, widget: relation, collection: staff, value_field: title, search_fields: [title]}
        - {label: "Teacher Link", name: teacherLink, widget: relation, collection: staff, value_field: linkHref, search_fields: [title]}
    - name: testimony
      label: Testimony
      folder: /content/testimonies
      media_folder: '/static/images/testimonies'
      public_folder: '/images/testimonies'
      create: true
      fields:
        - { name: title, label: title, required: true }
        - { name: college, label: college, required: false }
        - { name: image, label: img, widget: image, required: true }
        - { name: tags, label: classes, widget: select, multiple: true, options: ["SAT I", "SAT II", "College Consulting", "Classroom Prep", "ACT"], required: true }
        - { name: body, label: body, widget: markdown, required: true }
        - { name: featured, label: featured pages, widget: select, multiple: true, options: ["Home", "About Us", "Classroom Prep", "SAT", "College Consulting"], required: false }
    - name: pages
      label: Pages
      files:
       - name: home
         label: Home
         file: /content/pages/home.md
         media_folder: '/static/images/pages/home'
         public_folder: '/images/pages/home'
         fields:
          - {label: Title, name: title, widget: string}
          - label: Hero
            name: hero
            widget: object
            summary: '{{fields.name}}'
            fields:
               - {label: "Title", name: title, widget: string}
               - {label: "Description", name: description, widget: string}
               - {label: "Button Text", name: buttonText, widget: string}
               - {label: "Button Link", name: buttonLink, widget: string}
               - {label: "Image", name: image, widget: image}
          - label: Programs & classes
            name: classes
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Title", name: title, widget: string}
              - label: Class List
                name: classList
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: Image, name: icon, widget: code}
                  - {label: Description, name: description, widget: string}
                  - {label: Link Text, name: linkText, widget: string}
                  - {label: Link Href, name: linkHref, widget: string}
              - {label: "Class Schedule Link Text", name: linkText, widget: string}
              - {label: "Class Schedule Link Href", name: linkHref, widget: string}
          - label: About Us
            name: about
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Image", name: image, widget: image}
              - {label: "subtitle", name: subtitle, widget: string}
              - {label: "title", name: title, widget: string}
              - {label: "description", name: description, widget: string}
              - {label: "Link Text", name: linkText, widget: string}
              - {label: "Link Href", name: linkHref, widget: string}
          - label: Testimonies
            name: testimonies
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "subtitle", name: subtitle, widget: string}
              - {label: "Testimony Link Text", name: linkText, widget: string}
              - {label: "Testimony Link Href", name: linkHref, widget: string}
              - label: Testimony List
                name: testimonyList
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: College Icon, name: icon, widget: image}
                  - {label: Image, name: image, widget: image}
                  - {label: Classes, name: tags, widget: list }
                  - {label: Description, name: description, widget: string}
                  - {label: Quote, name: quote, widget: string}
          - label: Location
            name: location
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "subtitle", name: subtitle, widget: string}
              - {label: "title", name: title, widget: string}
              - label: Location List
                name: locationList
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: Description, name: description, widget: string}
                  - {label: "Link Text", name: linkText, widget: string}
                  - {label: "Link Href", name: linkHref, widget: string}
       - name: contact
         label: Contact Us
         file: /content/pages/contact.md
         media_folder: '/static/images/pages/contact'
         public_folder: '/images/pages/contact'
         fields:
          - {label: Title, name: title, widget: string}
          - label: Hero
            name: hero
            widget: object
            summary: '{{fields.name}}'
            fields: 
              - {label: "Title", name: title, widget: string}
              - {label: "Subtitle", name: subtitle, widget: string}
              - {label: "Description", name: description, widget: string}
              - {label: Form, name: form, widget: code}
          - label: Business Info
            name: business
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Title", name: title, widget: string}
              - label: Business Information
                name: businessInfoList
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: Description, name: description, widget: string}
       - name: about
         label: About
         file: /content/pages/about.md
         media_folder: '/static/images/pages/about'
         public_folder: '/images/pages/about'
         fields:
          - {label: "Title", name: title, widget: string}
          - label: Hero
            name: hero
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Title", name: title, widget: string}
              - {label: "Description", name: description, widget: string}
              - {label: "Button Text", name: buttonText, widget: string}
              - {label: "Button Link", name: buttonLink, widget: string}
              - {label: "Image", name: image, widget: image}
          - label: Why Lee's Review?
            name: reason
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Title", name: title, widget: string}
              - label: Reasons Why
                name: reasonsList
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: Description, name: description, widget: string}
          - label: Our Students
            name: students
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Image", name: image, widget: image}
              - {label: "Title", name: title, widget: string}
              - {label: "subtitle", name: subtitle, widget: string}
              - {label: "description", name: description, widget: string}
              - {label: "Link Text", name: linkText, widget: string}
              - {label: "Link Href", name: linkHref, widget: string}
          - label: Our Staff
            name: staff
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Title", name: title, widget: string}
              - label: Staff List
                name: staffList
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - {label: "name", name: title, widget: relation, collection: staff, value_field: title, search_fields: [title]}
                  - {label: "subtitle", name: subtitle, widget: relation, collection: staff, value_field: subtitle, search_fields: [title]}
                  - {label: "image", name: image, widget: relation, collection: staff, value_field: image, search_fields: [title]}
                  - {label: "classes", name: tags, widget: relation, collection: staff, value_field: tags, search_fields: [title]}
                  - {label: "description", name: description, widget: relation, collection: staff, value_field: description, search_fields: [title]}
                  - {label: "linkHref", name: linkHref, widget: relation, collection: staff, value_field: linkHref, search_fields: [title]}
                  - {label: "linkText", name: linkText, widget: relation, collection: staff, value_field: linkText, search_fields: [title]}
          - label: Our History
            name: history
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Title", name: title, widget: string}
       - name: testimonies
         label: Testimonies
         file: /content/pages/testimonies.md
         media_folder: /static/images/pages/testimonies
         public_folder: '/images/pages/testimonies'
         fields:
          - {label: Title, name: title, widget: string}
          - label: Hero
            name: hero
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Title", name: title, widget: string}
              - {label: "Description", name: description, widget: string}
              - {label: "Button Text", name: buttonText, widget: string}
              - {label: "Button Link", name: buttonLink, widget: string}
              - {label: "Image", name: image, widget: image}
       - name: sat
         label: SAT
         file: /content/pages/sat.md
         media_folder: '/static/images/pages/SAT'
         public_folder: '/images/pages/SAT'
         fields:
           - {label: Title, name: title, widget: string}
           - label: Hero
             name: hero
             widget: object
             summary: '{{fields.name}}'
             fields:
               - {label: "Title", name: title, widget: string}
               - {label: "Description", name: description, widget: string}
               - {label: "Button Text", name: buttonText, widget: string}
               - {label: "Button Link", name: buttonLink, widget: string}
               - {label: "Image", name: image, widget: image}
           - label: services
             name: servicesList
             widget: list
             summary: '{{fields.name}}'
             fields:
               - { name: title, label: title, required: true }
               - { name: image, label: img, widget: image, required: true }
               - { name: body, label: body, widget: markdown, required: true }
           - label: methods
             name: methodsList
             widget: list
             summary: '{{fields.name}}'
             fields:
               - { name: title, label: title, required: true }
               - { name: image, label: img, widget: image, required: true }
               - { name: body, label: body, widget: markdown, required: true }
           - label: Testimonies
             name: testimonies
             widget: object
             summary: '{{fields.name}}'
             fields:
               - {label: "subtitle", name: subtitle, widget: string}
               - {label: "Testimony Link Text", name: linkText, widget: string}
               - {label: "Testimony Link Href", name: linkHref, widget: string}
               - label: Testimony List
                 name: testimonyList
                 widget: list
                 summary: '{{fields.title}}'
                 fields:
                   - {label: Title, name: title, widget: string}
                   - {label: College Icon, name: icon, widget: image}
                   - {label: Classes, name: tags, widget: list }
                   - {label: Description, name: description, widget: string}
                   - {label: Quote, name: quote, widget: string}
           - label: price
             name: priceList
             widget: list
             summary: '{{fields.name}}'
             fields:
               - { name: title, label: title, required: true }
               - { name: price, label: price, widget: string, required: true }
               - { name: body, label: body, widget: markdown, required: true }
       - name: collegeConsulting
         label: College Consulting
         file: /content/pages/college-consulting.md
         media_folder: '/static/images/pages/college-consulting'
         public_folder: '/images/pages/college-consulting'
         fields:
           - {label: Title, name: title, widget: string}
           - label: Hero
             name: hero
             widget: object
             summary: '{{fields.name}}'
             fields:
               - {label: "Title", name: title, widget: string}
               - {label: "Description", name: description, widget: string}
               - {label: "Button Text", name: buttonText, widget: string}
               - {label: "Button Link", name: buttonLink, widget: string}
               - {label: "Image", name: image, widget: image}
           - label: services
             name: servicesList
             widget: list
             summary: '{{fields.name}}'
             fields:
               - { name: title, label: title, required: true }
               - { name: image, label: img, widget: image, required: true }
               - { name: body, label: body, widget: markdown, required: true }
           - label: methods
             name: methodsList
             widget: list
             summary: '{{fields.name}}'
             fields:
               - { name: title, label: title, required: true }
               - { name: image, label: img, widget: image, required: true }
               - { name: body, label: body, widget: markdown, required: true }
           - label: Testimonies
             name: testimonies
             widget: object
             summary: '{{fields.name}}'
             fields:
               - {label: "subtitle", name: subtitle, widget: string}
               - {label: "Testimony Link Text", name: linkText, widget: string}
               - {label: "Testimony Link Href", name: linkHref, widget: string}
               - label: Testimony List
                 name: testimonyList
                 widget: list
                 summary: '{{fields.title}}'
                 fields:
                   - {label: Title, name: title, widget: string}
                   - {label: College Icon, name: icon, widget: image}
                   - {label: Image, name: image, widget: image}
                   - {label: Classes, name: tags, widget: list }
                   - {label: Description, name: description, widget: string}
                   - {label: Quote, name: quote, widget: string}
           - label: price
             name: priceList
             widget: list
             summary: '{{fields.name}}'
             fields:
               - { name: title, label: title, required: true }
               - { name: price, label: price, widget: string, required: true }
               - { name: body, label: body, widget: markdown, required: true }
       - name: classroomPrep
         label: Classroom Prep
         file: /content/pages/classroomprep.md
         media_folder: '/static/images/pages/classroom-prep'
         public_folder: '/images/pages/classroom-prep'
         fields:
           - {label: Title, name: title, widget: string}
           - label: Hero
             name: hero
             widget: object
             summary: '{{fields.name}}'
             fields:
               - {label: "Title", name: title, widget: string}
               - {label: "Description", name: description, widget: string}
               - {label: "Button Text", name: buttonText, widget: string}
               - {label: "Button Link", name: buttonLink, widget: string}
               - {label: "Image", name: image, widget: image}
           - label: Additional Services
             name: servicesList
             widget: list
             summary: '{{fields.name}}'
             fields:
               - { name: title, label: title, required: true }
               - { name: image, label: img, widget: image, required: true }
               - { name: body, label: body, widget: markdown, required: true }