backend:
    name: git-gateway
    branch: master

media_folder: /static/images
public_folder: /images/

collections:
    - name: staff
      label: Staff
      folder: /content/staff
      create: true
      fields:
          - { name: title, label: title, required: true }
          - { name: position, label: position, required: true }
          - { name: description, label: Description, required: true }
          - { name: img, label: img, widget: image, media_folder: /static/images/staff, required: true }
          - { name: tags, label: classes, widget: list, required: true }
          - { name: color, label: color, widget: select, options: ["red", "orange", "green", "blue"], required: true }
          - { name: body, label: body, widget: markdown, required: true }
    - name: testimonies
      label: Testimonies
      folder: /content/testimonies
      create: true
      fields:
          - { name: title, label: title, required: true }
          - { name: college, label: college, required: false }
          - { name: img, label: img, widget: image, media_folder: /static/images/testimonies, required: true }
          - { name: color, label: color, widget: select, options: ["red", "orange", "green", "blue"], required: true }
          - { name: tags, label: classes, widget: list, required: true }
          - { name: body, label: body, widget: markdown, required: true }
    - name: pages
      label: Pages
      files:
       - name: home
         label: Home
         file: /content/pages/home.json
         fields:
          - {label: Title, name: title, widget: string}
          - label: Hero
            name: hero
            widget: object
            summary: '{{fields.name}}'
            fields:
               - {label: "Title", name: title, widget: string}
               - {label: "Description", name: description, widget: string}
               - {label: "Button Text", name: buttonText, widget: string}
               - {label: "Button Link", name: buttonLink, widget: string}
               - {label: "Image", name: image, widget: image, media_folder: /static/images/pages}
               - label: "Staff"
                 name: staff
                 widget: relation
                 collection: staff
                 value_field: title
                 search_fields: [title]
          - label: Programs & classes
            name: classes
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Title", name: title, widget: string}
              - label: Class List
                name: classList
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image, media_folder: /static/images/pages}
                  - {label: Image, name: icon, widget: code}
                  - {label: Description, name: descrtipion, widget: string}
                  - {label: Link Text, name: linkText, widget: string}
                  - {label: Link Href, name: linkHref, widget: string}
              - {label: "Class Schedule Link Text", name: linkText, widget: string}
              - {label: "Class Schedule Link Href", name: linkHref, widget: string}
          - label: About Us
            name: about
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Image", name: image, widget: image, media_folder: /static/images/pages}
              - {label: "subtitle", name: subtitle, widget: string}
              - {label: "title", name: title, widget: string}
              - {label: "description", name: description, widget: string}
              - {label: "Link Text", name: linkText, widget: string}
              - {label: "Link Href", name: linkHref, widget: string}
          - label: Testimonies
            name: testimonies
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "Testimony Link Text", name: linkText, widget: string}
              - {label: "Testimony Link Href", name: linkHref, widget: string}
              - label: Testimony List
                name: classList
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image, media_folder: /static/images/pages}
                  - {label: Description, name: descrtipion, widget: string}
                  - {label: Quote, name: Quote, widget: string}
          - label: Location
            name: location
            widget: object
            summary: '{{fields.name}}'
            fields:
              - {label: "subtitle", name: subtitle, widget: string}
              - {label: "title", name: title, widget: string}
              - label: Location List
                name: locationList
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Descrtipion, name: description, widget: string}
                  - {label: "Link Text", name: linkText, widget: string}
                  - {label: "Link Href", name: linkHref, widget: string}
       - name: contact
         label: Contact Us
         file: /content/pages/contact.json
         fields:
          - {label: Title, name: title, widget: string}